FROM node:20-slim AS build

WORKDIR /app

COPY package.json package-lock.json /app/
RUN npm ci

COPY . /app/

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

RUN npm run build

FROM node:20-slim

WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json /app/
RUN npm ci --omit=dev

COPY --from=build /app/dist /app/dist

EXPOSE 5006
ENV PORT=5006

CMD ["npm", "run", "start"]
